name: study_mates
description: "A modern academic companion app for COMSATS students, offering study materials, discussion forums, and productivity tools."
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.6.2 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    google_fonts: ^6.1.0
    intl: ^0.18.1
    firebase_core: ^2.24.0
    firebase_auth: ^4.17.0
    cloud_firestore: ^4.15.0
    provider: ^6.1.1
    fluttertoast: ^8.2.4
    uuid: ^4.5.0
    http: ^1.2.1
    google_sign_in: ^6.1.1
    firebase_auth_web: ^5.8.13
    file_picker: ^6.1.1
    path_provider: ^2.1.1
    open_filex: ^4.5.0
    flutter_pdfview: ^1.3.2
    permission_handler: ^11.3.1
    shared_preferences: ^2.2.3
    shared_preferences_web: ^2.2.0
    firebase_storage: ^11.7.7
    flutter_spinkit: ^5.2.1
    connectivity_plus: ^6.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - image/about.jpg
        - image/logo.png
    plugin:
        platforms:
            linux:
                default_package: file_picker_desktop
            macos:
                default_package: file_picker_desktop
            windows:
                default_package: file_picker_desktop